const JADWAL_STATUS = {
	AKTIF: 'aktif',
	BELUM_AKTIF: 'belum-aktif',
	SELESAI: 'selesai',
};

export const JADWAL_STATUS_DESCRIPTION = {
	[JADWAL_STATUS.AKTIF]: 'Aktif',
	[JADWAL_STATUS.BELUM_AKTIF]: 'Belum Aktif',
	[JADWAL_STATUS.SELESAI]: 'Selesai',
};

export const JADWAL_STATUS_LIST = [
	{ id: JADWAL_STATUS.AKTIF, nama: JADWAL_STATUS_DESCRIPTION[JADWAL_STATUS.AKTIF] },
	{ id: JADWAL_STATUS.BELUM_AKTIF, nama: JADWAL_STATUS_DESCRIPTION[JADWAL_STATUS.BELUM_AKTIF] },
	{ id: JADWAL_STATUS.SELESAI, nama: JADWAL_STATUS_DESCRIPTION[JADWAL_STATUS.SELESAI] },
];

export default JADWAL_STATUS;
